image:
  file: .gitpod.Dockerfile
checkoutLocation: "go/src/github.com/cockroachdb/cockroach"
# tasks:
#   - init: |
#       go get github.com/spf13/cobra/cobra
#       go build
#     command: |
#       ./mycli --help
vscode:
  extensions:
    - golang.go
